<div class="container">
    <h2>All Posts</h2>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Id</th>
            <th>Author</th>
            <th>Title</th>
            <th>Content</th>
            <th>Pubdate</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $key => $value): ?>
        <tr>
            <td><?= $value['id'] ?></td>
            <td><?= $value['id_author'] ?></td>
            <td><?= $value['title'] ?></td>
            <td><?= $value['content'] ?></td>
            <td><?= $value['pubdate'] ?></td>
        </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
</div>
<nav aria-label="Page navigation">
    <ul class="pagination">
        <li>
            <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
            <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
